# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch

# Create random tensor
random_tensor = torch.rand(7,7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
another_tensor = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(random_tensor, another_tensor.T)
# Perform matrix multiplication


tensor([[1.4754],
        [2.2435],
        [1.0140],
        [1.6546],
        [1.1622],
        [1.4530],
        [1.7147]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
import random
RANDOM_SEED=0

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
random_tensor = torch.rand(7,7)
torch.manual_seed(seed=RANDOM_SEED)
another_tensor = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(random_tensor, another_tensor.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
RANDOM_SEED=1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# device

# Create two random tensors on GPU
torch.manual_seed(seed=RANDOM_SEED)
tensor_A = torch.rand(2,3)
torch.manual_seed(seed=RANDOM_SEED)
tensor_B = torch.rand(2,3)
tensor_on_gpu = tensor_A.to(device)
tensor_on_gpu
another_tensor_on_gpu = tensor_B.to(device)
another_tensor_on_gpu

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
output = torch.matmul(tensor_A,tensor_B.T)
output

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

### 8. Find the maximum and minimum values of the output of 7.

In [11]:
# Find max
output.max()
# Find min
output.min()


tensor(0.2161)

### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max
output.argmax()

# Find arg min
output.argmin()


tensor(1)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [14]:
# Set seed
RANDOM_SEED=7

# Create random tensor
torch.manual_seed(seed=RANDOM_SEED)
random_tensor = torch.rand(1,1,1,10)

# Remove single dimensions
torch.manual_seed(seed=RANDOM_SEED)
updated_tensor = random_tensor.squeeze()

# Print out tensors and their shapes
random_tensor, random_tensor.shape, updated_tensor, updated_tensor.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))